version: '3.8'

services:
  postgres:
    container_name: nest-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: case
      PGDATA: /data/postgres    
    volumes:
      - ./data/pg:/data/postgres
  
  redis:
    container_name: nest-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data